[tool.pyright]
include = [
  "**/troposphere",
]
pythonPlatform = "All"
pythonVersion = "3.8"
reportDuplicateImport = "none"
reportImportCycles = "none"
reportIncompatibleMethodOverride = "warning"
reportMissingTypeStubs = "none"
reportPrivateUsage = "none"
reportUnknownMemberType = "none"
reportUnnecessaryIsInstance = "none"
reportUnusedImport = "none"
reportUnusedVariable = "none"
reportWildcardImportFromLibrary = "none"
strict = [
  "**/__init__.py"
]
strictParameterNoneValue = false
typeCheckingMode = "off"
useLibraryCodeForTypes = true
venv = ".venv"
